apiVersion: v1
kind: ConfigMap
metadata:
  name: product
data:
  SPRING_PROFILES_ACTIVE: secret
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: product
  namespace: dev-server
  labels:
    k8s-app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: product
  template:
    metadata:
      name: product
      labels:
        k8s-app: product
    spec:
      containers:
        - name: product
          image: local-repo/product:test1
          ports:
            - containerPort: 8890 #runs on port 8890 inside the pod, so any request made to the pod at the port 8890 should be received by this product service
            - containerPort: 4452
          env:
            - name: SPRING_PROFILES_ACTIVE  #this value follows a format like: spring.profiles.active -> SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: product #checks the "product" config map to get the value
                  key: SPRING_PROFILES_ACTIVE #This is the value defined in the config map
            - name: CONSUL_IP
              value: ${CONSUL_SERVICE_HOST} #This value will be populated by kubernetes once a service resource is created. To check all the values type "env" inside any container
            - name: CONSUL_PORT
              value: ${CONSUL_SERVICE_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: dev-server
  labels:
    k8s-app: product
spec:
  selector: #The selector is the one which tells where the service should map. We are targeting "product" deployment by using app selector label
    k8s-app: product
  ports:
    - name: tcp-8890-product
      protocol: TCP
      port: 8890
    - name: tcp-4452-product
      protocol: TCP
      port: 4452
  type: ClusterIP # ClusterIP exposes services accessible within the kubernetes cluster