version: '2.2'
services:
  customer:
    image: myproject/customer:latest
    ports:
      - 8090:8090
    command:
      - java
      - -Djava.security.egd=file:/dev/./urandom
      #- -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7878
      - -jar
      - /customer.jar

  shop:
    image: myproject/shop:latest
    ports:
      - 8080:8080
    command:
      - java
      - -Djava.security.egd=file:/dev/./urandom
      #- -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7878
      - -jar
      - /shop.jar